### ISSUE TITLE
Problem connecting from OBS to nginx

### ISSUE THREAD

**Issue by Majow** [Noxalus/Multi-Streaming-Server#1]
Hi, i'm using Vagrant and finally i've been able to start everything up all good, even connect to the stats page without a problem, BUT, When I try to connect with OBS, it just disconnects me in a second. (OBS or OBS/MP, same problem)

I dont know where I'm doing wrong. :(

Pastebin with nginx.conf: http://pastebin.com/5AP5uiR3
Imgur Stats page: http://i.imgur.com/KyqrWr9.jpg

Sorry if i'm making some dumb mistake.

**Comment by Noxalus** [comment]
Hi, and thank you for your interest in this project!

What did you enter as RTMP URL into OBS?

**Comment by Majow** [comment]
rtmp://192.168.42.42:1935/live

Screenshot: http://i.imgur.com/a8kth19.jpg
Error after about a second: http://i.imgur.com/UWVdXcX.jpg
Yesterday i've also received "rtmpsockbuf_fill" as an error

(Thank you for making this project, I'm growing my channel and would like to use it so I can reach wider audiences.. It's simply perfect for me)

**Comment by Noxalus** [comment]
The URL seems to be correct.

I struggle a loooooong time with this error before to setup the VM network properly, but Vagrant will do it for you.

Can you check that the VM is accessible on the same network than yours? (open a Windows command prompt and type `ping 192.168.42.42` for instance).

You can also try to disable your firewall or any software that could interfere.

Do you use the master branch? If yes, you can try to switch to the _chat_ branch to see if the error is the same as last resort.

**Comment by Noxalus** [comment]
Ok, I know why you have this error. I use this project on an online server, and I don't want that someone (other than me) can publish a RTMP stream, so I made an IP restriction in the **live** application. That corresponds to **allow publish** and **deny publish** statements, and in your conf, you put this:

```
application live {
    live on;
    record off;

    allow publish 127.0.0.1;
    deny publish all;

    [...]
}
```

But 127.0.0.1 is the local address of the virtual machine, and I think that you publish your stream from the host (your PC) instead. So you need to replace 127.0.0.1 by the LAN IP (`ipconfig` in a command prompt to find it, it should looks like that => 192.168.X.X). But if you use this project in local only, you can also simply remove this two lines.

I hope that it will works for you, and waiting for confirmation before to close this issue. :)

**Comment by Majow** [comment]
Deleting the two lines TOTALLY WORKED! Thank you very much! I appreciate your help very much! ;D

**Comment by Noxalus** [comment]
I'm glad to hear that! Let me know if you have any problem again ;)
