### ISSUE TITLE
Facebook Live?

### ISSUE THREAD

**Issue by Kanbei85** [Noxalus/Multi-Streaming-Server#12]
Can this be used for facebook live streaming also? I do not see any settings for it in the nginx.conf file

**Comment by Noxalus** [comment]
Hello 😄 

I didn't test it, but it should work, all you need to do is to replace the RTMP URL by the one provided by Facebook. Make sure to append the stream key to this URL too 😉 

Let me know here if you successfully tested it, I'm curious.

**Comment by Noxalus** [comment]
I've had the opportunity to test Facebook Live service with this project, and as I expected, it's pretty fast forward.

I've written a wiki page about that [here](https://github.com/Noxalus/Multi-Streaming-Server/wiki/How-to-handle-new-services). Let me know if it's good to you too ;)
