### ISSUE TITLE
not pushing to facebook

### ISSUE THREAD

**Issue by ewertonhm** [Noxalus/Multi-Streaming-Server#17]
https://i.imgur.com/RsfF3jC.png

it seens to be ok, but nothing show on my facebook live, here is my .conf:

`#user  nobody;
worker_processes  1;
 
error_log  logs/error.log  debug;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;
pid        logs/nginx.pid;

 
events {
    worker_connections  1024;
}

http {
    include             mime.types;
    default_type        application/octet-stream;

    sendfile            on;
    keepalive_timeout   65;

    server {
        listen          8080;
        server_name     localhost;

        # rtmp stat
        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            # you can move stat.xsl to a different location
            root html;
        }

        # rtmp control
        location /control {
            rtmp_control all;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
 
rtmp {
    server {
        listen 1935;
        chunk_size 8192;

        application live {
            live on;
            record off;
            			
            push rtmp://localhost/facebook/${name};
        }

		application facebook {
			live on;
			record off;

			push rtmp://live-api-a.facebook.com:80/2415039085192327?s_ps=1&s_sw=0&s_vt=api-s&a=AbwIId-qcTTVEkLA;
		}
    }
}`

**Comment by Noxalus** [comment]
Hello, 

I didn't test Facebook live, but from what I see, the RTMP URL is this: `rtmp://live-api-a.facebook.com:80/rtmp/`

So you should do something like that instead: `push rtmp://live-api-a.facebook.com:80/rtmp/2415039085192327?s_ps=1&s_sw=0&s_vt=api-s&a=AbwIId-qcTTVEkLA;`

**Comment by ewertonhm** [comment]
yes, my mistake, forget the /rtmp/
