### ISSUE TITLE
Multi Instances

### ISSUE THREAD

**Issue by eaba** [Noxalus/Multi-Streaming-Server#18]
Can multi instances be created?

**Comment by Noxalus** [comment]
Hello,

I didn't test, but probably not.

Why would you like to have multiple instances?

**Comment by eaba** [comment]
Just wondering if something like youtube or facebook live streaming can be achieved.
Each user having her own push endpoint

**Comment by Noxalus** [comment]
That's the exact purpose of this project! You can have multiple endpoint for multiple services 👍

**Comment by eaba** [comment]
Please can you show samples?
Can it be done dynamically without restarting nginx?
What doing something like stream keys, that is authentications?
I would appreciate any help from you?
Thanks!

**Comment by Noxalus** [comment]
I've written a wiki page that explains how it work [here](https://github.com/Noxalus/Multi-Streaming-Server/wiki/How-to-handle-new-services) 😉

**Comment by eaba** [comment]
Would that work in a multiple source(user) platform like facebook? Won't reloading the configuration affect other streams(users)?

**Comment by Noxalus** [comment]
Hum, I'm not sure to understand what you are saying. Do you mean that with Facebook, multiple users can stream to the same live? 🤔 I don't really see how it could work 😮 

But the purpose of this project is to broadcast the stream from a single source to multiple services, if you  want another source at the same time, you can try to add another [live](https://github.com/Noxalus/Multi-Streaming-Server/blob/master/nginx/conf/nginx.template.conf#L52) application in the Nginx configuration file, but if you send the stream to the same service with the same keys, I don't really now what will happen when both sources will send a stream at the same time 😰

**Comment by eaba** [comment]
Basically multiple sources to multiple services
