### ISSUE TITLE
Nginx not starting with "vagrant up"

### ISSUE THREAD

**Issue by sigvenss** [Noxalus/Multi-Streaming-Server#3]
The setup is working great, and im streaming to 3 different streaming services!

But i just have a quick question:

When ill start streaming do i have to run "vagrant up" and then "vagrant provision" to get the VM up and Nginx starting?

If i only run vagrant up, it does not start Nginx, but if i do "vagrant provision" it starts checking for VM updates, and then it starts Nginx. 
Do you have any tips on how i should start the VM and Nginx without downloading ALOT of updates everytime i wanna stream?

**Comment by sigvenss** [comment]
I contacted Noxalu by email and i got this answer:

> When you do a "vagrant up" for the first time, it automatically runs a "vagrant provision", so you shouldn't have to run "vagrant provision" yourself.
> 
> All you need to do is a "vagrant up" when you want to launch the Nginx RTMP server. If you look at the bootstrap.sh script (here => https://github.com/Noxalus/Multi-Streaming-Server/blob/master/bootstrap.sh#L49), you can see that we set the script to launch Nginx at startup. So when you turn on your VM (via "vagrant up"), it should launch the Nginx RTMP server automatically. If it's not the case, it's a bug.
> 
> What you can do is to ssh you on the VM (via "vagrant ssh") and launch the service manually with this command: sudo service nginx start.

Doing vagrant SSH did not work for me since im running it on windows, got error that it could not find an ssh client. 
But i started VirtualBox and logged in to the VM manually.
Then i ran the command you suggested(sudo service nginx start) and now it works great :)

**Comment by Noxalus** [comment]
I'm on Windows too, but I use Cygwin (with OpenSSH module) so I can run "vagrant ssh".

But it's not the ideal solution, I will try to find out why it doesn't work as expected.

I now it's also possible to execute some shell commands at "vagrant up" updating the _Vagrant_ file, it can be a better temporary solution.

Currently, I'm not on my environment, so I need to install all dependencies, but I will come back to you when I have more information.

**Comment by Noxalus** [comment]
Ok, I've just tested, and it seems to work as expected for me.

When I run _vagrant up_, I can directly connect to the RTMP server with OBS. If I run _vagrant halt_, I'm disconnected, but if I run _vagrant up_ again, OBS will reconnect automatically when the VM is up.

What made you say that the RTMP server was not launched after a _vagrant up_? You couldn't connect to it with OBS after a _vagrant up_?

**Comment by dwbstreet** [comment]
Thanks in advance for all your efforts. I am having difficulties. When I run  vagrant up from cmd everything appears to initialize. Then after it forwards ports it tries to ssh into the VM. "This may take a few minutes..."  It times out every time. Please advise. I installed Virtual Box and Vagrant on Windows 10 64 and further installed the Mainline nginx. Thanks so much.

**Comment by Noxalus** [comment]
Hello @dwbstreet, can you give me the versions of VirtualBox and Vagrant that you use (I've just tested it a few minutes ago, and I don't have th problem. I use VirtualBox 5.0.16 and Vagrant 1.8.1).

**Comment by dwbstreet** [comment]
Greetings,

Thanks so much for the prompt reply.
I am using Oracle VM Virtual Box Version 5.1.2 r 108956
Vagrant 1.8.5

**Comment by dwbstreet** [comment]
Just saw this error on Virtual Box. VT-x/AMD-V hardware acceleration is not available on your system. Your 64-bit guest will fail to detect a 64-bit CPU and will not be able to boot.

**Comment by Noxalus** [comment]
Indeed, you need to enable virtualization in your BIOS to use VirtualBox properly. A lot of tutorial show you how to do it on the net ([this one for example](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Virtualization_Administration_Guide/sect-Virtualization-Troubleshooting-Enabling_Intel_VT_and_AMD_V_virtualization_hardware_extensions_in_BIOS.html)).

**Comment by dwbstreet** [comment]
thanks so much, I am searching the BIOS

**Comment by dwbstreet** [comment]
The machine is now launching properly! Thank you.
Now, I am not able to configure the nginx.conf properly.
Could you specify which lines need to be altered to my inputs, please. 
I have grown extremely frustrated, although I have learned.

**Comment by Noxalus** [comment]
You need to replace each `{{ variable_name }}` in the [Nginx configuration file](https://github.com/Noxalus/Multi-Streaming-Server/blob/master/nginx/conf/nginx.template.conf) by your personal information. That's the case for:

- `{{ my_ip_address }}` (you can remove this line if you don't deploy the script on an online server)
- `{{ youtube_key }}`
- `{{ dailymotion_key }}`
- `{{ hitbox_key }}`
- `{{ twitch_key }}`

If you don't want to stream for a specific service, let's say Dailymotion for instance, you can remove the `application dailymotion { [...] }` block entirely.
