### ISSUE TITLE
Restart just one service

### ISSUE THREAD

**Issue by Majow** [Noxalus/Multi-Streaming-Server#4]
Hi, I know it's not your main concern, if you have the time, could you make a way somehow I can restart the stream just for 1 service?

I've been streaming to youtube/hitbox/twitch lately, one day youtube was "frozen" and the others seemed fine, so I stopped OBS and started the stream again. Obviously all my streams were gone for the time. It would be amazing if I could just restart one specific stream.

I know you are a busy person so dont worry much about it.

Also, sorry if I didnt find the right place to post this.

PS: amazing job you've done so far. I'm loving it.

**Comment by Noxalus** [comment]
Hi,

I'm glad to know that this script is useful to someone else :)

I think it won't be as easy as it sounds to do what you want. If the other services work fine, the stream that you send from OBS is correct, so it shouldn't freeze with Youtube neither. Except if you don't push the stream directly (if you use FFMpeg to transcode the stream for instance). Is it your case ? Is your server powerfull enough to run FFMpeg on a live stream?

If you use **push** directive, and that the stream is disconnected, it will try to reconnect within the next 3 seconds as said in the Nginx RTMP module [official documentation](https://github.com/arut/nginx-rtmp-module/wiki/Directives#push_reconnect).
