### ISSUE TITLE
Issue with remote connection

### ISSUE THREAD

**Issue by EasyAsABC123** [Noxalus/Multi-Streaming-Server#5]
i'm using vagrant and it appear to be working, i'm connecting to the machine over ssh and can see the server up and running.

Change in Vagrantfile

```
config.vm.network "public_network"
```

OBS connects just fine, to the public IP however external IPs cannot connect to the RTMP stream.  Is this something wrong with my virtualbox driver? or anything you would know? the stats page shows the inbound data and then I can stream the content locally and it shows the output...it just doesn't work over the network externally (not sure if internally from another computer either, i'll check that tomorrow).  I'll also test this on another computer.

**Comment by Noxalus** [comment]
Sorry, I'm not sure to understand what you want to do actually. You say that you can't connect to the RTMP stream from external IPs, but you want to read or push the stream data?

If you want to read the stream, I don't really know how to do it, but I suppose that you need a server that handle RTMP protocol and push to the URL corresponding to this server into your _nginx.conf_ file.

If you want to write the stream, please make sure that the [**allow publish**](https://github.com/Noxalus/Multi-Streaming-Server/blob/master/nginx/conf/nginx.template.conf#L56) directive contains the external IP.

**Comment by EasyAsABC123** [comment]
No I'm writing to the stream locally.  Then from an external IP someone else will read from it.  You can do this with a flash client or with ffplay/ffmpeg

Justin Schuhmann

**Comment by Noxalus** [comment]
Ok, I see now. Did you try adding a directive `allow play all;` in the _live_ application? (just after the _allow publish_ directive for instance).

**Comment by Noxalus** [comment]
You should also try enabling HLS:

```
hls on;
hls_nested on;
hls_path /hsl/live;
hls_fragment 10s;
```

**Comment by EasyAsABC123** [comment]
I don't need to do that when basically doing the same vagrant steps by
hand...it only happens when i'm using this vagrant

**Comment by EasyAsABC123** [comment]
I redid the steps by hand and it works fine...issue with vagrant or the NAT + Public IP
