### ISSUE TITLE
Vagrant twitch

### ISSUE THREAD

**Issue by dwbstreet** [Noxalus/Multi-Streaming-Server#8]
Noxalus, thanks so much for all of your time.

I sincerely appreciate you assisting me in getting the Virtual Box up and running!

My connection to twitch is encountering problems. It is connecting fine, but the encoder is not functioning properly.
This is the message I am receiving:
Max keyframe interval is currently at 8.0 seconds. Please set it to 2 seconds.
The broadcast is not set to constant bitrate (CBR). [Current average: 1896 kbps, current max: 2559.124 kbps"

**Comment by Noxalus** [comment]
Hello,

If you also use FFMpeg to encode your stream to Twitch (like in the default configuration of this project), you can specify the keyframe using some additional paramaters:

`-x264-params keyint=60:no-scenecut=1`

The value of `keyint` should be the max keyframe you want \* FPS. So for a max keyinterval of 2 and with a stream locked to 30 FPS, the value of `keyint` will be `2 * 30 = 60`.

[(source)](http://stackoverflow.com/questions/30979714/how-to-change-keyframe-interval-in-ffmpeg)

Same thing to use a constant bitrate, you need to use a new parameter:

`-x264opts bitrate=3500:vbv-maxrate=3500:vbv-bufsize=116`
- `vbv-maxrate` = bitrate = B = target bitrate
- `vbv-bufsize` = B / fps (in this video's case that's 30 fps)

[(source)](http://stackoverflow.com/questions/7125446/encoding-h-264-cbr-videos-with-ffmpeg)

At the end, you should have something like that in your Nginx configuration file:

```
exec ffmpeg -i rtmp://localhost/$app/$name -c:v libx264 -preset veryfast -c:a copy 
    -b:v 3500k 
    -bufsize 3500k
    -maxrate 3500k 
    -s 1280x720 -r 30
    -x264-params keyint=60:no-scenecut=1:bitrate=3500:vbv-maxrate=3500:vbv-bufsize=116
    -f flv rtmp://localhost/twitch/$name;
```

I didn't test the solutions here and I'm not an expert of FFMpeg. I advise you to look at the [FFMpeg official documentation](https://ffmpeg.org/ffmpeg.html) if you still have some problems with your stream encoding.

Let me know if it works as expected ;)

**Comment by dwbstreet** [comment]
Thanks so much. After updating the config the twitch account showed excellent at first connection. After I refreshed the page, this changed to acceptable and listed the same issues (CBR not constant, Keyframe 8). I don't understand..

**Comment by dwbstreet** [comment]
Here is a screenshot of the twitch video statistics directly: 
![image](https://cloud.githubusercontent.com/assets/20062929/17560213/3095b260-5eef-11e6-97e5-40f39a982206.png)
I have both my original feed from OBS and the Vagrant config set to 30fps, not 60. I noticed that today, as well.
