### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Majow** [Noxalus/Multi-Streaming-Server#9]
I've been running it for almost 4 months without a problem, but funny enough yesterday it gave me an error right before I went streaming.

> D:\Multi-Streaming-Server-master>vagrant version
> Installed Version: 1.8.5
> Latest Version: 1.8.5
> 
> You're running an up-to-date version of Vagrant!
> 
> D:\Multi-Streaming-Server-master>vagrant reload
> ==> default: Checking if box 'ubuntu/trusty64' is up to date...
> ==> default: Clearing any previously set forwarded ports...
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
>     default: Adapter 2: hostonly
> ==> default: Forwarding ports...
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
> The guest machine entered an invalid state while waiting for it
> to boot. Valid states are 'starting, running'. The machine is in the
> 'poweroff' state. Please verify everything is configured
> properly and try again.
> 
> If the provider you're using has a GUI that comes with it,
> it is often helpful to open that and watch the machine, since the
> GUI often has more helpful error messages than Vagrant can retrieve.
> For example, if you're using VirtualBox, run `vagrant up` while the
> VirtualBox GUI is open.
> 
> The primary issue for this error is that the provider you're using
> is not properly configured. This is very rarely a Vagrant issue.

I actually tried deleting everything and just keeping my nginx config file. But the same error happens!

Could you help me? :(

**Comment by Noxalus** [comment]
Did you change something related to your VirtualBox installation ?

Did you try to destroy and up your box again (with a `vagrant destroy` then `vagrant up`).

**Comment by Majow** [comment]
the only difference between last week and today is that someday midweek I updated Windows 10 with the anniversary update. I didn't really 'vagrant up' right after, so can't say it's exactly that. I know I did not  made anything related exclusively to virtualbox before the error appearing. Of course I tried a vagrant box update to update virtualbox to 1.8.5, but the error was there before :(

**Comment by Noxalus** [comment]
I didn't make the Anniversary update yet, but for some reason it seems to break VirtualBox virtual machines. ([see here](http://superuser.com/questions/1111027/fix-vagrant-up-after-windows-10-anniversary-update/1111028)).

Make sure to update both Vagrant and VirtualBox to their latest version and try to reboot your host machine like said in the link above.

**Comment by Majow** [comment]
I think we are back!! Thank you so much for answering me so quickly. I did update vagrant and virtualbox, than restarted and it appears to be working again!

**Comment by Noxalus** [comment]
Glad to know that. :smile:
